services:
  - type: web
    name: ecg-digitizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: FLASK_ENV
        value: production
    autoDeploy: true
